### ISSUE TITLE
Dear sir, can you please tell me  why I got this  error : shape '[128, 1, 640, 2]' is invalid for input of size 81920

### ISSUE THREAD

**Issue by SIN5t** [mingyuyng/Deep-JSCC-for-images-with-OFDM#6]
I use the default param to run the training, but got this err:

  x = x.view(N, self.opt.P, (Ns+self.opt.N_pilot)*(self.opt.M+self.opt.K), 2)
RuntimeError: shape '[128, 1, 640, 2]' is invalid for input of size 81920

If you happen to know the solution, could you please give me some tips？ Thank you very much !!!

**Comment by WenBingo** [comment]
> I use the default param to run the training, but got this err:
> 
> x = x.view(N, self.opt.P, (Ns+self.opt.N_pilot)*(self.opt.M+self.opt.K), 2) RuntimeError: shape '[128, 1, 640, 2]' is invalid for input of size 81920
> 
> If you happen to know the solution, could you please give me some tips？ Thank you very much !!!

想问下你解决了吗？我这边当时使用的时候需要将torch.ifft()改为torch.fft.ifft() ， 感觉像是pytroch版本的问题

**Comment by SIN5t** [comment]
@WenBingo 没有，这个包我也改了，感觉应该是数据集和参数的问题

**Comment by WenBingo** [comment]
> @WenBingo 没有，这个包我也改了，感觉应该是数据集和参数的问题

我查了torch.fft.ifft()的手册。修改为torch.fft.ifft(x, dim=1, norm="forward")  就可以，但这样并不完全等价于旧版的torch.ifft()，后续处理还是会遇到问题。只能等作者回复pytorch的版本号，或者解答了

**Comment by WenBingo** [comment]
> @WenBingo 没有，这个包我也改了，感觉应该是数据集和参数的问题

我不知道明白ifft，但是原先的输入是最后是 2理解是表示复数，但是经过ifft为什么最后还是2维?ifft后不应该是时域吗?

**Comment by WenBingo** [comment]
> @WenBingo 没有，这个包我也改了，感觉应该是数据集和参数的问题

改不出来，之前改的有问题
x = torch.fft.ifft(x, 1 )
 x = torch.stack((x.real, x.imag), -1)
这样修改后还是有问题
哎..............

**Comment by SIN5t** [comment]
复数指的是图片降采样后信号本身是复数信号而不是和傅里叶变换有关系？

**Comment by WenBingo** [comment]
> 复数指的是图片降采样后信号本身是复数信号而不是和傅里叶变换有关系？

18921762605这我微信号，能一起交流复现问题吗

**Comment by WenBingo** [comment]
> 复数指的是图片降采样后信号本身是复数信号而不是和傅里叶变换有关系？

兄弟，你有什么解决办法吗？卡在torch.ifft（）这debug不下去了

**Comment by WenBingo** [comment]
> I use the default param to run the training, but got this err:
> 
> x = x.view(N, self.opt.P, (Ns+self.opt.N_pilot)*(self.opt.M+self.opt.K), 2) RuntimeError: shape '[128, 1, 640, 2]' is invalid for input of size 81920
> 
> If you happen to know the solution, could you please give me some tips？ Thank you very much !!!

兄弟，你有明白作者为什么torch.ifft(x, 1 ) 在一维度上进行ifft吗？我看别人对原始图片比如3*64*64，都是对dim=（-2， -1）进行ifft的

**Comment by mingyuyng** [comment]
Hi @WenBingo and @SIN5t. Thanks for the discussion. I realized that torch.fft and torch.ifft are not supported by Pytorch anymore. So I changed them to torch.fft.fft and torch.fft.ifft. The environment information is also included in the Readme file. Now I can successfully run the command in the Readme file. Please let me know if you guys still face the same errors.

**Comment by SIN5t** [comment]
Thank you very much! You're so kind，I will continue to learn from your paper，wishing you all the best in your studies and career!
